basePath: /
host: localhost:8000
info:
  contact:
    email: julianlee107@hotmail.com
    name: Julian Lee
  description: 用gin框架搭建一个博客api.
  title: Swagger Example API
  version: "1.0"
paths: {}
securityDefinitions:
  JWT:
    authorizationUrl: ""
    flow: application
    scopes:
      write: ' Grants write access'
    tokenUrl: 127.0.0.1:8000/auth
    type: oauth2
swagger: "2.0"
